apiVersion: apps/v1
kind: Deployment
metadata:
  name: wastes-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wastes-app
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0%
  template:
    metadata:
      labels:
        app: wastes-app
    spec:
      containers:
      - image: wastes:1.1
        name: wastes
---
apiVersion: v1
kind: Service
metadata:
  name: wastes-service
spec:
  type: LoadBalancer
  selector:
    app: wastes-app
  ports:
  - port: 8100